SELECT
    PFUNC.CODCOLIGADA,
    PFUNC.CHAPA,
    PFUNC.NOME,
    PFUNC.SALARIO AS SALARIO_ATUAL,
    PFUNC.SALARIO * :AUMENTO / 100 AS AUMENTO_SALARIAL,
    (PFUNC.SALARIO +( PFUNC.SALARIO * :AUMENTO / 100)) AS SALARIO_CORRIGIDO,
    PFUNCAO.NOME AS FUNCAO,    
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO AS SECAO, 
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    PPESSOA.SEXO,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO   
FROM 
    PPESSOA (NOLOCK)
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA  
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
WHERE 
    PFUNC.CODSITUACAO <> 'D'
    AND PFUNCAO.CODIGO <> '369'
ORDER BY
    PFUNC.NOME,
    PFUNC.CHAPA;
