SELECT  
    PFUNC.NOME AS NOME,
    PFUNC.CHAPA AS CHAPA,
    PFUNC.CODSECAO AS SEXO,
    PSECAO.DESCRICAO AS DESC_SECAO,
    PFUNC.CODFUNCAO AS FUNCAO,
    PFUNCAO.NOME AS DESC_FUNCAO,
    PFDEPEND.NRODEPEND AS NRO_DEPENDENTE,
    PFDEPEND.NOME AS NOME_DEPENDENTE,
    CONVERT(VARCHAR(12), PFDEPEND.DTNASCIMENTO, 103) AS DT_NASCIMENTO,

    CASE PFDEPEND.CARTAOVACINA
        WHEN '1' THEN 'SIM'
        ELSE 'NÃO'
    END AS CARTAO_VACINA,

    CASE PFDEPEND.FREQESCOLAR
        WHEN '1' THEN 'SIM'
        ELSE 'NÃO'
    END AS FREQ_ESCOLAR

FROM 
    PFUNC (NOLOCK)
JOIN  
    PFUNCAO (NOLOCK) 
    ON PFUNCAO.CODIGO = PFUNC.CODFUNCAO 
    AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA 
    -- NOME DA FUNÇÃO

INNER JOIN 
    PSECAO (NOLOCK) 
    ON PFUNC.CODSECAO = PSECAO.CODIGO 
    AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA 
    -- NOME DA SEÇÃO

INNER JOIN 
    PFDEPEND (NOLOCK) 
    ON PFDEPEND.CODCOLIGADA = PFUNC.CODCOLIGADA 
    AND PFUNC.CHAPA = PFDEPEND.CHAPA

WHERE 
    PFUNC.CODCOLIGADA = '1' 
    AND PFUNC.CODSITUACAO <> 'D'
    AND PFDEPEND.GRAUPARENTESCO = '1'

GROUP BY  
    PFUNC.CODCOLIGADA, 
    PFUNC.CHAPA, 
    PFUNC.CODSECAO, 
    PSECAO.DESCRICAO,
    PFUNC.CODFUNCAO,
    PFUNC.NOME,
    PFUNCAO.NOME,
    PFDEPEND.NRODEPEND,
    PFDEPEND.NOME,
    PFDEPEND.CARTAOVACINA,
    PFDEPEND.FREQESCOLAR,
    PFDEPEND.DTNASCIMENTO

ORDER BY  
    PFUNC.CODSECAO, 
    PFUNC.CHAPA, 
    PFUNC.CODFUNCAO;


		--select * from pfdepend where chapa = '0100386'

