SELECT 
    PFUNC.CODCOLIGADA,  
    CONVERT(VARCHAR(12), PPESSOA.DTNASCIMENTO, 103) AS DATA_NASCIMENTO,
    PPESSOA.CPF,
    PPESSOA.CARTIDENTIDADE,
    VCONSULTASPRONT.CHAPA AS MATRICULA,  
    PFUNC.NOME AS NOME_FUNCIONARIO,  
    PSECAO.DESCRICAO AS SETOR,  
    PFUNCAO.NOME AS FUNCAO,  
    CONVERT(VARCHAR(12), PFUNC.DATAADMISSAO, 103) AS DATA_ADMISSAO,  
    VEXAMES.NOMEEXAME,  
    CONVERT(VARCHAR(12), MAX(CAST(VCONSULTASPRONT.DATAASO AS DATE)), 103) AS DATA_ULTIMO_ASO,  
    CONVERT(VARCHAR(12), DATEADD(YEAR, 1, MAX(CAST(VCONSULTASPRONT.DATAASO AS DATE))), 103) AS PROXIMO_EXAME,    
    CASE  
        WHEN DATEADD(YEAR, 1, MAX(CAST(VEXAMESPRONT.DATAEXAME AS DATE))) < CAST(GETDATE() AS DATE) THEN 'VENCIDO'  
        WHEN DATEADD(YEAR, 1, MAX(CAST(VEXAMESPRONT.DATAEXAME AS DATE))) <= DATEADD(DAY, 45, CAST(GETDATE() AS DATE)) THEN 'REVISAR'  
        ELSE 'VÁLIDO'  
    END AS STATUS,  
    VTIPOCONSULTA.DESCRICAO AS TIPO_EXAME    
FROM VCONSULTASPRONT (NOLOCK)  
JOIN PFUNC (NOLOCK)  
    ON PFUNC.CODPESSOA = VCONSULTASPRONT.CODPESSOA  
    AND PFUNC.CHAPA = VCONSULTASPRONT.CHAPA  
    AND PFUNC.CODCOLIGADA = VCONSULTASPRONT.CODCOLIGADA 
JOIN PPESSOA (NOLOCK)
	ON PPESSOA.CODIGO = VCONSULTASPRONT.CODPESSOA	
JOIN VEXAMESPRONT (NOLOCK)  
    ON VCONSULTASPRONT.IDCONSULTA = VEXAMESPRONT.IDCONSULTA  
JOIN VEXAMES (NOLOCK)  
    ON VEXAMES.CODEXAME = VEXAMESPRONT.CODEXAME  
JOIN VTIPOCONSULTA (NOLOCK)  
    ON VTIPOCONSULTA.CODCLIENTE = VCONSULTASPRONT.CODTIPOCONSULTA  
JOIN PSECAO (NOLOCK)  
    ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA  
    AND PSECAO.CODIGO = PFUNC.CODSECAO  
JOIN PFUNCAO (NOLOCK)  
    ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA  
    AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO  
WHERE 
    PFUNC.CODCOLIGADA = 1  
    AND PFUNC.CODSITUACAO <> 'D' 
GROUP BY  
    PFUNC.CODCOLIGADA,  
    VCONSULTASPRONT.CHAPA,
    PPESSOA.DTNASCIMENTO, 
    PPESSOA.CPF,
    PPESSOA.CARTIDENTIDADE,
    PFUNC.NOME,  
    PSECAO.DESCRICAO,  
    PFUNCAO.NOME,  
    PFUNC.DATAADMISSAO,  
    VEXAMES.NOMEEXAME,  
    VTIPOCONSULTA.DESCRICAO  
HAVING DATEADD(YEAR, 1, MAX(CAST(VEXAMESPRONT.DATAEXAME AS DATE))) BETWEEN :DATAINICIAL AND :DATAFINAL
ORDER BY  
    PFUNC.NOME,  
    VEXAMES.NOMEEXAME;
