DECLARE @ANO_INICIAL INT = :ANO_INICIAL -- Substitua pelo input do usuário
DECLARE @ANO_FINAL INT = :ANO_FINAL -- Substitua pelo input do usuário

SELECT 
    PSECAO.DESCRICAO AS SETOR,
    YEAR(PFUNC.DATAADMISSAO) AS ANO_ADMISSAO,
    YEAR(PFUNC.DATADEMISSAO) AS ANO_DEMISSAO,
    COUNT(DISTINCT CASE 
        WHEN YEAR(PFUNC.DATAADMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL 
        THEN PFUNC.CHAPA 
    END) AS TOTAL_ADMISSOES,
    COUNT(DISTINCT CASE 
        WHEN YEAR(PFUNC.DATADEMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL 
        THEN PFUNC.CHAPA 
    END) AS TOTAL_DESLIGAMENTOS,
    COUNT(DISTINCT CASE 
        WHEN YEAR(PFUNC.DATAADMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL 
        THEN PFUNC.CHAPA 
    END) - COUNT(DISTINCT CASE 
        WHEN YEAR(PFUNC.DATADEMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL 
        THEN PFUNC.CHAPA 
    END) AS SALDO_LIQUIDO
FROM PFUNC (NOLOCK)
JOIN PSECAO (NOLOCK) 
    ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA 
    AND PSECAO.CODIGO = PFUNC.CODSECAO 
WHERE PFUNC.CODCOLIGADA = 1  
    AND (YEAR(PFUNC.DATAADMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL 
         OR YEAR(PFUNC.DATADEMISSAO) BETWEEN @ANO_INICIAL AND @ANO_FINAL)
GROUP BY 
    PSECAO.DESCRICAO,
    YEAR(PFUNC.DATAADMISSAO),
    YEAR(PFUNC.DATADEMISSAO)
ORDER BY 
    ANO_ADMISSAO DESC, SALDO_LIQUIDO DESC;
