WITH UltimasFerias AS (
    SELECT 
        CHAPA, 
        MAX(DATAFIM) AS ULTIMA_DATAFIM
    FROM 
        PFUFERIASPER (NOLOCK)
    GROUP BY 
        CHAPA
)
SELECT
    PFUNC.CHAPA,
    PFUNC.NOME,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DATA_ADMISSAO,
    CONVERT(VARCHAR, UF.ULTIMA_DATAFIM, 103) AS ULTIMA_FIM_FERIAS,
    CASE
        WHEN UF.ULTIMA_DATAFIM IS NULL THEN
            CASE 
                WHEN DATEADD(YEAR, 1, PFUNC.DATAADMISSAO) < GETDATE() THEN 'FÉRIAS VENCIDAS'
                ELSE 'FÉRIAS EM DIA'
            END
        ELSE
            CASE 
                WHEN DATEADD(YEAR, 1, UF.ULTIMA_DATAFIM) < GETDATE() THEN 'FÉRIAS VENCIDAS'
                ELSE 'FÉRIAS EM DIA'
            END
    END AS STATUS_FERIAS
FROM 
    PFUNC (NOLOCK)
LEFT JOIN 
    UltimasFerias UF ON PFUNC.CHAPA = UF.CHAPA
WHERE 
    PFUNC.CODSITUACAO IN ('A', 'F')
ORDER BY 
    PFUNC.CHAPA;
