SELECT
    PFUNC.CODCOLIGADA,			
    PFUNC.CHAPA,
    PFUNC.NOME,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,
    PFCODFIX.CODEVENTO AS COD,
    PEVENTO.CODRUBRICA AS CODRUBRICA,
    --PEVENTO.CODIGO  AS CODEVENTO,
    PEVENTO.DESCRICAO AS DESCRICAO,
    PFCODFIX.VALOR AS VALOR,      
    CASE  -- Cálculo das parcelas restantes
        WHEN PFCODFIX.ANOINICIO IS NULL OR PFCODFIX.ANOFIM IS NULL 
            THEN 0 -- Caso ANO_INICIO ou ANO_FIM sejam NULL, não há parcelas restantes
        WHEN (YEAR(GETDATE()) > PFCODFIX.ANOFIM) OR (YEAR(GETDATE()) = PFCODFIX.ANOFIM AND MONTH(GETDATE()) > PFCODFIX.MESFIM)
            THEN 0 -- Já passou da última parcela
        WHEN (YEAR(GETDATE()) < PFCODFIX.ANOINICIO) OR (YEAR(GETDATE()) = PFCODFIX.ANOINICIO AND MONTH(GETDATE()) < PFCODFIX.MESINICIO)
            THEN ((PFCODFIX.ANOFIM - PFCODFIX.ANOINICIO) * 12 + PFCODFIX.MESFIM - PFCODFIX.MESINICIO + 1) -- Nenhuma parcela paga ainda
        ELSE 
            ((PFCODFIX.ANOFIM - PFCODFIX.ANOINICIO) * 12 + PFCODFIX.MESFIM - PFCODFIX.MESINICIO + 1) -
            ((YEAR(GETDATE()) - PFCODFIX.ANOINICIO) * 12 + MONTH(GETDATE()) - PFCODFIX.MESINICIO)
    END AS PARCELAS_RESTANTES,    
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO
FROM 
    PPESSOA (NOLOCK) 
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA 
JOIN 
    PFCODFIX (NOLOCK) ON PFUNC.CHAPA = PFCODFIX.CHAPA 
JOIN 
     PEVENTO (NOLOCK) ON  PEVENTO.CODIGO  = PFCODFIX.CODEVENTO    
WHERE
	PFUNC.CODSITUACAO <> 'D'
    AND PFCODFIX.CODEVENTO = :CODIGO_EVENTO     
ORDER BY 
    PFUNC.CHAPA;
