SELECT
    PFUNC.CODCOLIGADA,			
    PFUNC.CHAPA AS CHAPA,
    PFUNC.NOME AS NOME,
    PSECAO.DESCRICAO AS SECAO, 
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,
    PPESSOA.GRAUINSTRUCAO,
    PCODINSTRUCAO.DESCRICAO,
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO
FROM 
    PPESSOA (NOLOCK) 
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
JOIN 
	PCODINSTRUCAO (NOLOCK) ON PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODINTERNO
WHERE
    PFUNC.CODSITUACAO NOT IN ('D', 'I', 'T', 'P')   
ORDER BY 
    PFUNC.CHAPA;
