SELECT
	PFUNC.CODCOLIGADA,
    PFUNC.CHAPA,
    PFUNC.NOME,
    PFUNCAO.NOME AS FUNCAO,
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO AS SECAO, 
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    PPESSOA.SEXO,
    CASE PPESSOA.DEFICIENTEFISICO
     	WHEN 1 THEN 'SIM'
     	ELSE 'NAO'
    END AS [DEFICIENTE FISICO],	    
    CASE PPESSOA.DEFICIENTEAUDITIVO
     	WHEN 2 THEN 'SIM'
     	ELSE 'NAO'
    END AS [DEFICIENTE AUDITIVO],	
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,
    CONVERT(VARCHAR, PFUNC.DATADEMISSAO, 103) AS DTDEMISSAO,    	
    COUNT(1) AS QT		
FROM 
    PPESSOA (NOLOCK)
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA  
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
WHERE 
    PPESSOA.DEFICIENTEFISICO <> 0 
    OR PPESSOA.DEFICIENTEAUDITIVO <> 0    
GROUP BY 
    PFUNC.CHAPA,
    PFUNC.NOME,
    PFUNCAO.NOME,
    PFUNC.CODSECAO,
    PFUNC.CODSITUACAO,
    PSECAO.DESCRICAO, 
    PPESSOA.SEXO,
    PPESSOA.DEFICIENTEFISICO,
    PPESSOA.DEFICIENTEAUDITIVO,
    PFUNC.DATAADMISSAO,
    PFUNC.DATADEMISSAO,
    PFUNC.CODCOLIGADA
ORDER BY 
    PFUNC.CHAPA;
