SELECT 	PFUNC.CHAPA,
		PFUNC.NOME,
		PFUNCAO.NOME AS FUNCAO,
		PFUNC.CODSECAO,
		PPESSOA.CPF, 
		PSECAO.DESCRICAO AS SECAO, 
		CASE PFUNC.CODSITUACAO
        	WHEN 'D' THEN 'DEMITIDO'
	        WHEN 'A' THEN 'ATIVO'
	        WHEN 'F' THEN 'FERIAS'
	        WHEN 'P' THEN 'AF. PREVIDENCIA'
	        WHEN 'W' THEN 'LICEN MATERN 180d'
	        WHEN 'C' THEN 'CONTRATO SUSPENSO'
	        WHEN 'E' THEN 'LICEN MATERNIDADE'
	        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
	        WHEN 'M' THEN 'SERVIÇO MILITAR'
	        WHEN 'R' THEN 'LICEN REMUNERADA'
	        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
	        WHEN 'V' THEN 'AVISO PREVIO'
	        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
	        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    	END AS SITUACAO,
		PFUNC.SALARIO,
		PPESSOA.TELEFONE1, 
		PPESSOA.TELEFONE2,
		PPESSOA.TELEFONE3,
		PPESSOA.SEXO, 
		CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,
   		CONVERT(VARCHAR, PFUNC.DATADEMISSAO , 103) AS DTDEMISSAO,
		PFUNC.CODCOLIGADA,	
		COUNT(1) AS QT		
FROM 
    PPESSOA (NOLOCK) 
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA  
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
WHERE PFUNC.CODSITUACAO = 'A'
    
GROUP BY PFUNC.CHAPA,
		PFUNC.NOME,
		PFUNCAO.NOME,
		PFUNC.CODSECAO,
		PFUNC.CODSITUACAO,
		PSECAO.DESCRICAO, 
		PFUNC.SALARIO,
		PPESSOA.CPF, 
		PPESSOA.SEXO,
		PFUNC.DATAADMISSAO,
		PFUNC.CODCOLIGADA,
		PPESSOA.TELEFONE1, 
		PPESSOA.TELEFONE2,
		PPESSOA.TELEFONE3,
		CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103),
    	CONVERT(VARCHAR, PFUNC.DATADEMISSAO , 103)
ORDER BY PFUNC.CHAPA

		
		


--WHERE PFUNC.DATAADMISSAO  BETWEEN :DATAINICAL AND :DATAFINAL
