SELECT distinct
	PFUNC.CODCOLIGADA as COLIGADA,
	PFUNC.CHAPA,
	PFUNC.CODSITUACAO STATUS,
	PFUNC.NOME AS NOME_FUNCIONARIO,
	PFUNCAO.NOME FUNCAO,
	PFUNC.CODSECAO,
	PSECAO.DESCRICAO,
	CONVERT (VARCHAR,  pfunc.dataadmissao, 103) AS DTADMISSAO,
	PFDEPEND.NOME DEPENDENTE,
	PFDEPEND.CPF AS [CPF DEPENDENTE],
	PFDEPEND.SEXO AS [SEXO DEPENDENTE],
	CONVERT (VARCHAR,  PFDEPEND.DTNASCIMENTO, 103) AS [DTNASCIMENTO DEPENDENTE],
	DATEDIFF(hour, PFDEPEND.DTNASCIMENTO, getdate()) / 8766 AS [IDADE DEPENDENTE],
	CASE PFDEPEND.GRAUPARENTESCO
		WHEN '1' THEN 'FILHO(A) VÁLIDO' 
		WHEN '3' THEN 'FILHO(A) INVÁLIDO' 
		WHEN '5' THEN 'CÔNJUGE' 
		WHEN '6' THEN 'PAI' 
		WHEN '7' THEN 'MÃE' 
		WHEN '8' THEN 'SOGRO(A)' 
		WHEN '9' THEN 'OUTROS' 
		WHEN 'A' THEN 'AVÔ(Á)' 
		WHEN 'C' THEN 'COMPANHEIRO(A)' 
		WHEN 'D' THEN 'ENTEADO(A)' 
		WHEN 'E' THEN 'EXCLUÍDO' 
		WHEN 'G' THEN 'EX-CONJUGE' 
		WHEN 'I' THEN 'IMRÃO VÁLIDO' 
		WHEN 'N' THEN 'IRMÃO INVÁLIDO' 
		WHEN 'P' THEN 'EX-COMPANHEIRO(A)' 
		WHEN 'S' THEN 'EX-SOGRO(A)' 
		WHEN 'T' THEN 'NETO(A)' 
		WHEN 'X' THEN 'EX-ENTEADO(A)' 
		END AS GRAUPARENTESCO,
	CASE PFDEPEND.INCIRRF
		WHEN '1' THEN 'SIM'
		ELSE 'NÃO'
	END AS INCID_IRRF
FROM PPESSOA (NOLOCK) 
JOIN PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA  
JOIN PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA AND GCOLIGADA.CODCOLIGADA = PFUNCAO.CODCOLIGADA
LEFT JOIN PFDEPEND (NOLOCK) ON PFDEPEND.CHAPA = PFUNC.CHAPA  
WHERE
	PFUNC.CODSITUACAO IN ('A', 'F')
	AND PFDEPEND.GRAUPARENTESCO IN ('1','3')
	AND PPESSOA.SEXO = 'F'
	AND PFUNC.CODCOLIGADA = :CODCOLIGADA
ORDER BY
	PFUNC.CHAPA