SELECT DISTINCT
    PFUNC.CODCOLIGADA AS COLIGADA,
    PFUNC.CHAPA AS CHAPA,
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    PFUNC.NOME AS NOME_FUNCIONARIO,
    PFUNCAO.NOME AS FUNCAO,
    PFUNC.CODSECAO AS SETOR,
    PSECAO.DESCRICAO AS DESCRICAO_SETOR,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,
    CONVERT(VARCHAR, PFUNC.FIMPRAZOCONTR, 103) AS [FIM_DO_1_PRAZO],
    CONVERT(VARCHAR, DATEADD(DAY, 60, PFUNC.FIMPRAZOCONTR), 103) AS [FIM_DO_2_PRAZO] -- Fim do segundo prazo
FROM 
    PPESSOA (NOLOCK)
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
JOIN 
    GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA AND GCOLIGADA.CODCOLIGADA = PFUNCAO.CODCOLIGADA
WHERE
    PFUNC.CODSITUACAO NOT IN ('D', 'I', 'T', 'P')
    AND PFUNC.FIMPRAZOCONTR BETWEEN :INICIODOPRAZO AND :FIMDOPRAZO -- Contratos a vencer no período especificado
    OR DATEADD(DAY, 60, PFUNC.FIMPRAZOCONTR) BETWEEN :INICIODOPRAZO AND :FIMDOPRAZO
    AND PFUNC.CODCOLIGADA = :CODCOLIGADA
ORDER BY
    PFUNC.CHAPA;
