SELECT
    PFUNC.CHAPA,
    PFUNC.NOME,
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    CONVERT(VARCHAR,PFUNC.DTVENCFERIAS,103) AS [VENCIMENTO DE FERIAS]    
FROM 
    PFUNC (NOLOCK)
WHERE 
    PFUNC.CODSITUACAO <> 'D'
    AND PFUNC.CODCOLIGADA = :CODCOLIGADA    
ORDER BY
PFUNC.NOME,
PFUNC.DTVENCFERIAS,
PFUNC.CHAPA;
