SELECT
    PFUNC.CODCOLIGADA,			
    PFUNC.CHAPA,
    PPESSOA.CPF,
    PFUNC.NOME,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO,         
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    PFFINANC.CODEVENTO,
    PEVENTO.DESCRICAO AS DESCRICAO_EVENTO,
    PFUNCAO.NOME AS FUNCAO,
	PFUNC.CODSECAO,
	PSECAO.DESCRICAO AS SECAO,
	PPESSOA.CPF, 	 
    PFFINANC.VALOR,
    PFFINANC.ANOCOMP,
    PFFINANC.MESCOMP,
    PFFINANC.NROPERIODO
FROM 
    PPESSOA (NOLOCK) 
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA 
JOIN
    PFFINANC (NOLOCK) ON PFUNC.CHAPA = PFFINANC.CHAPA 
JOIN 
    PEVENTO (NOLOCK) ON PFFINANC.CODEVENTO = PEVENTO.CODIGO  
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
WHERE
     PFFINANC.ANOCOMP = :ANO
    AND PFFINANC.MESCOMP = :MES
    AND PFFINANC.NROPERIODO = :PERIODO    
ORDER BY
    PFUNC.NOME, 
    PFUNC.CHAPA;
