SELECT 
    PFUNC.CODCOLIGADA AS COLIGADA,
    PFUNC.CHAPA,
    CASE PFUNC.CODSITUACAO
        WHEN 'D' THEN 'DEMITIDO'
        WHEN 'A' THEN 'ATIVO'
        WHEN 'F' THEN 'FERIAS'
        WHEN 'P' THEN 'AF. PREVIDENCIA'
        WHEN 'W' THEN 'LICEN MATERN 180d'
        WHEN 'C' THEN 'CONTRATO SUSPENSO'
        WHEN 'E' THEN 'LICEN MATERNIDADE'
        WHEN 'I' THEN 'APOSENTADO INVALIDEZ'
        WHEN 'M' THEN 'SERVIÇO MILITAR'
        WHEN 'R' THEN 'LICEN REMUNERADA'
        WHEN 'T' THEN 'AFASTADO AC. TRABALHO'
        WHEN 'V' THEN 'AVISO PREVIO'
        WHEN 'O' THEN 'DOENÇA OCUPACIONAL'
        ELSE 'OUTRO_CONSULTAR_CADASTRO'
    END AS SITUACAO,
    PFUNC.NOME AS NOME_FUNCIONARIO,
    PFUNCAO.NOME AS FUNCAO,
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO,
    CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103) AS DTADMISSAO, 
    CONVERT(VARCHAR, PFUFERIASPER.DATAINICIO, 103) AS [INICIO FERIAS], 
    CONVERT(VARCHAR, PFUFERIASPER.DATAFIM, 103) AS [FIM FERIAS],   
    COUNT(1) AS quantidade
FROM 
    PPESSOA (NOLOCK) 
JOIN 
    PFUNC (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA  
JOIN 
    PFUNCAO (NOLOCK) ON PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
JOIN 
    PSECAO (NOLOCK) ON PFUNC.CODSECAO = PSECAO.CODIGO
JOIN 
    PFUFERIASPER (NOLOCK) ON PFUNC.CHAPA = PFUFERIASPER.CHAPA
WHERE
    PFUNC.CODCOLIGADA = :CODCOLIGADA
    AND PFUNC.CHAPA = :CHAPA    	
GROUP BY  
    PFUNC.CODCOLIGADA,
    PFUNC.CHAPA,
    PFUNC.CODSITUACAO,
    PFUNC.NOME,
    PFUNCAO.NOME,
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO,
    PFUFERIASPER.DATAINICIO, 
    PFUFERIASPER.DATAFIM, 
    PFUNC.DATAADMISSAO    
ORDER BY
    PFUNC.CHAPA;
