SELECT DISTINCT
    VCONSULTASPRONT.CODCOLIGADA,
    VCONSULTASPRONT.CHAPA AS MATRICULA,
    PFUNC.NOME AS NOME_FUNCIONARIO,
    CONVERT(VARCHAR(12), VCONSULTASPRONT.DATACONSULTA, 103) AS DATA_ASO,
    VEXAMESPRONT.DATAEXAME AS DATA_EXAME,
    VTIPOCONSULTA.DESCRICAO AS TIPO_EXAME,
    VEXAMES.NOMEEXAME

FROM VCONSULTASPRONT (NOLOCK)
JOIN PFUNC (NOLOCK) 
    ON PFUNC.CODPESSOA = VCONSULTASPRONT.CODPESSOA 
    AND PFUNC.CHAPA = VCONSULTASPRONT.CHAPA
    AND PFUNC.CODCOLIGADA = VCONSULTASPRONT.CODCOLIGADA
    AND PFUNC.CODSITUACAO = 'A'  -- Apenas funcionários ATIVOS

INNER JOIN VEXAMESPRONT (NOLOCK) 
    ON VCONSULTASPRONT.IDCONSULTA = VEXAMESPRONT.IDCONSULTA

INNER JOIN VTIPOCONSULTA (NOLOCK) 
    ON VTIPOCONSULTA.CODCLIENTE = VCONSULTASPRONT.CODTIPOCONSULTA

INNER JOIN VEXAMES (NOLOCK) 
    ON VEXAMES.CODEXAME = VEXAMESPRONT.CODEXAME

WHERE 
    PFUNC.CODCOLIGADA = 1  -- Apenas Coligada 1
    AND YEAR(VEXAMESPRONT.DATAEXAME) = :ANO  -- Substitua ":ANO" pelo ano desejado
	 AND month(VEXAMESPRONT.DATAEXAME) = :MES
ORDER BY 
    VEXAMESPRONT.DATAEXAME DESC;


